# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-09 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'permissions': (('repository.index', 'repository.index'), ('repository.app_index', 'repository.app_index'), ('repository.cls_index', 'repository.cls_index'), ('repository.add_model_obj', 'repository.add_model_obj'), ('repository.add_model_obj:POST', 'repository.add_model_obj:POST'), ('repository.action_model_obj:POST', 'repository.action_model_obj:POST'), ('repository.delete_model_obj:POST', 'repository.delete_model_obj:POST'), ('repository.delete_collection:POST', 'repository.delete_collection:POST'), ('repository.cls_index@UserInfo', 'repository.cls_index@UserInfo'))},
        ),
    ]
