# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-02 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('summary', models.TextField(null=True, verbose_name='简介')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('detail', models.TextField(verbose_name='文章内容')),
                ('index_kind', models.IntegerField(choices=[(1, '技术'), (2, '新闻'), (3, '其他')], default=2, verbose_name='总分类')),
                ('read', models.IntegerField(default=0, verbose_name='阅读量')),
            ],
            options={
                'verbose_name_plural': '文章表',
                'db_table': 'ArticleInfo',
            },
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=30, verbose_name='个性签名')),
                ('title', models.CharField(max_length=10, verbose_name='博客标题')),
            ],
            options={
                'verbose_name_plural': '个人博客表',
                'db_table': 'BlogInfo',
            },
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.BlogInfo', verbose_name='所属博客'),
        ),
    ]
